# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20170105_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.AddField(
            model_name='dog',
            name='guts',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='history',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='tall',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='live',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
