# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_auto_20170105_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
