# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_dog_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='weight',
        ),
    ]
