# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0005_remove_dog_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='kg',
            field=models.CharField(default=2, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
