# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_dog_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='guts',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dog',
            name='kg',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dog',
            name='live',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dog',
            name='tall',
            field=models.CharField(max_length=128),
        ),
    ]
