# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161228_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
