# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
