# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
